### ISSUE TITLE
Talespire will not start with these plugins

### ISSUE THREAD

**Issue by Gulharun** [LordAshes/Talespire-AudioPlugin#2]
Heya, I'm using your plugins AudioPlugin and Tabletop RPG Music (which depends on the AudioPlugin) and I get an infinite loading screen. Just wanna help put it out there so I can continue using the mod, great work on it by the way!

What I've tried so far:
Uninstalling/reinstalling
Installing manually
Disabling all mods and running just those two
Disabling every mod one by one to find the culprit 
Using the previous versions

**Comment by LordAshes** [comment]
Most plugins are broken due to BR update. We are working on it.

Lord Ashes

**Comment by Itachi118** [comment]
I assumed you guys knew but seeing I am not the only one having this problem and that you guys are working on it is a huge load off my chest. Thanks!!

**Comment by HolloFox** [comment]
This can be resolved.
