### ISSUE TITLE
Recent TaleSpire update

### ISSUE THREAD

**Issue by equanimittyy** [LordAshes/Talespire-AudioPlugin#5]
Recent TaleSpire update has broken the AudioPlugin, no longer plays with any mod packs.

![image](https://github.com/LordAshes/Talespire-AudioPlugin/assets/104692345/28626342-a416-46ad-9bb3-c8a259f2c4d1)

**Comment by LordAshes** [comment]
Update your BepInEx to the latest version and then apply the BepInEx config
change as detailed on the Unofficial Talespire Modding Discord and you will
be good to go.

Lord Ashes

**Comment by equanimittyy** [comment]
I see, thank you, fixed indeed works. For anyone experiencing issues in the future, refer to the Unofficial Talespire Modding Discord (which can be found through the official Talespire discord), and refer to the pins in #general.
